version: '3.3'
services:
  database:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: 'DBProjet1'
      MYSQL_USER: 'U'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: '--init-file /data/application/init.sql'
    volumes:
        - ./docker/images/mysql/schema/init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
      - '33060:33060'
    expose:
      - '3306'
  app:
    image: ghcr.io/amt-14/test_amt_team_14:latest
    ports:
      - '9080:9080'
      - '7777:7777'
    links:
      - "database:db"
    volumes:
    - ./src/main/liberty/config/server.xml:/config/server.xml
    depends_on:
      - api_gamification
      - database

  database_gamification:
    image: mysql:8.0.21
    container_name: db_gamification
    restart: always
    environment:
      MYSQL_USER: 'APIUser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'DBProjet2'
    ports:
      - '3305:3306'

  api_gamification:
    container_name: api_gamification
    image: ghcr.io/amt-14/gamificationapi_image:latest
    ports:
      - '8088:8080'
    depends_on:
      - database_gamification
    environment:
      MYSQL_HOST: 'database_gamification'
      MYSQL_PASSWORD: 'password'
      MYSQL_PORT: 3306
      MYSQL_USER: 'APIUser'
      MYSQL_DATABASE: 'database_gamification'
