version: '3.3'
services:
  db:
    image: ./docker/image/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    image: ghcr.io/amt-14/jdbc_test:latest
    ports:
      - '9080:9080'
    links:
      - "db:database"
