version: '3.3'
services:
  database:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: 'DBProjet1'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - ./docker/images/mysql/schema/init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    image: ghcr.io/amt-14/jdbc_test:latest
    ports:
      - '9080:9080'
    links:
      - "database:db"
