
name: build and publish Docker image

on: 
  push:
    branches: [ jdbc ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo $GITHUB_ACTOR

    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
       java-version: 11

    - uses: actions/cache@v1
      with : 
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn clean package


    - name: Build Dockerimage (includes mvn clean package)
      run: |
       echo ${{ secrets.AMT_14_TEAM_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
       docker build -t amt-14/jdbc_test .
       docker tag amt-14/jdbc_test ghcr.io/amt-14/jdbc_test
       docker push ghcr.io/amt-14/jdbc_test
